# GoReleaser configuration for AgentManager
# Documentation: https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  # CLI binary - Linux only (CGO required for systray)
  - id: agentmgr-linux
    main: ./cmd/agentmgr
    binary: agentmgr
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # CLI binary - cross-compile without CGO for Darwin/Windows
  - id: agentmgr-nocgo
    main: ./cmd/agentmgr
    binary: agentmgr
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # Helper binary - Linux only (CGO required for systray)
  - id: agentmgr-helper-linux
    main: ./cmd/agentmgr-helper
    binary: agentmgr-helper
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # Note: agentmgr-helper is not cross-compiled - it requires darwinkit and CGO
  # For Darwin and Windows, users should build from source or use native builds

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
      - catalog.json

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999

release:
  github:
    owner: kevinelliott
    name: agentmanager
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  header: |
    ## AgentManager v{{.Version}}

    ### Installation

    **macOS (Homebrew)**
    ```bash
    brew install kevinelliott/tap/agentmanager
    ```

    **Download Binary**
    Download the appropriate binary for your platform from the assets below.

    **Go Install**
    ```bash
    go install github.com/kevinelliott/agentmanager/cmd/agentmgr@v{{.Version}}
    ```

brews:
  - name: agentmanager
    repository:
      owner: kevinelliott
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    homepage: "https://github.com/kevinelliott/agentmanager"
    description: "CLI tool for managing AI development agents"
    license: "MIT"
    skip_upload: auto
    test: |
      system "#{bin}/agentmgr", "version"
    install: |
      bin.install "agentmgr"
      bin.install "agentmgr-helper"

nfpms:
  - id: packages
    package_name: agentmanager
    vendor: Kevin Elliott
    homepage: https://github.com/kevinelliott/agentmanager
    maintainer: Kevin Elliott <kevin@kevinelliott.com>
    description: CLI tool for managing AI development agents
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: ./catalog.json
        dst: /usr/share/agentmgr/catalog.json
        type: config

announce:
  skip: true
